
services:
  postgresql: 
    image: 'bitnami/postgresql'
    container_name: shopper-database
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE}
    networks:
      - shopper

  api-shopper:
    build:
      context: .
    container_name: api-shopper
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    networks:
      - shopper

volumes:
  db:

networks:
  shopper:
    driver: bridge